/** ILO-ISIC Rev. 4 division codes and labels for industry/sector selection */
export interface IloIsicDivision {
  code: string;
  label: string;
}

export const ILO_ISIC_DIVISIONS: IloIsicDivision[] = [
  { code: "01", label: "Crop and animal production, hunting" },
  { code: "03", label: "Fishing and aquaculture" },
  { code: "05", label: "Mining of coal and lignite" },
  { code: "06", label: "Extraction of crude petroleum and natural gas" },
  { code: "07", label: "Mining of metal ores" },
  { code: "08", label: "Other mining and quarrying" },
  { code: "10", label: "Manufacture of food products" },
  { code: "11", label: "Manufacture of beverages" },
  { code: "12", label: "Manufacture of tobacco products" },
  { code: "13", label: "Manufacture of textiles" },
  { code: "14", label: "Manufacture of wearing apparel" },
  { code: "15", label: "Manufacture of leather and related products" },
  { code: "16", label: "Manufacture of wood and wood products" },
  { code: "17", label: "Manufacture of paper and paper products" },
  { code: "18", label: "Printing and recording" },
  { code: "19", label: "Manufacture of coke and refined petroleum" },
  { code: "20", label: "Manufacture of chemicals and chemical products" },
  { code: "21", label: "Manufacture of pharmaceuticals" },
  { code: "22", label: "Manufacture of rubber and plastic products" },
  { code: "23", label: "Manufacture of non-metallic mineral products" },
  { code: "24", label: "Manufacture of basic metals" },
  { code: "25", label: "Manufacture of fabricated metal products" },
  { code: "26", label: "Manufacture of computer, electronic and optical products" },
  { code: "27", label: "Manufacture of electrical equipment" },
  { code: "28", label: "Manufacture of machinery and equipment" },
  { code: "29", label: "Manufacture of motor vehicles" },
  { code: "30", label: "Manufacture of other transport equipment" },
  { code: "31", label: "Manufacture of furniture" },
  { code: "32", label: "Other manufacturing" },
  { code: "35", label: "Electricity, gas, steam and air conditioning" },
  { code: "41", label: "Construction of buildings" },
  { code: "45", label: "Wholesale and retail trade and repair of motor vehicles" },
  { code: "49", label: "Land transport and transport via pipelines" },
  { code: "55", label: "Accommodation" },
  { code: "56", label: "Food and beverage service activities" },
  { code: "58", label: "Publishing activities" },
  { code: "62", label: "Computer programming and consultancy" },
  { code: "64", label: "Financial service activities" },
  { code: "68", label: "Real estate activities" },
  { code: "70", label: "Management consultancy activities" },
  { code: "85", label: "Education" },
  { code: "86", label: "Human health activities" },
  { code: "87", label: "Residential care activities" },
];
