/** Metric ids included in PESTEL SOURCE A digest and year/figure grounding checks. */
export const PESTEL_DIGEST_KEYS: readonly string[] = [
  "gdp",
  "gdp_ppp",
  "gdp_per_capita",
  "gdp_per_capita_ppp",
  "gdp_growth",
  "population",
  "inflation",
  "gov_debt_pct_gdp",
  "unemployment_ilo",
  "labor_force_total",
  "life_expectancy",
  "pop_age_0_14",
  "pop_age_65_plus",
  "pop_15_64_pct",
  "literacy_adult",
  "undernourishment",
  "poverty_headcount",
  "poverty_national",
  "enrollment_primary_pct",
  "enrollment_secondary",
  "enrollment_tertiary_pct",
  "completion_tertiary",
  "edu_expenditure_gdp",
  "lending_rate",
];
