/**
 * Starter prompts for Analytics Assistant — aligned with routing and data scope:
 * - **Focus metrics** → dashboard / WDI snapshot, rankings, comparisons
 * - **Current affairs** → live web verification (leadership, elections, news)
 * - **Place & society** → web-first; avoids irrelevant macro padding when not asked
 * - **Data literacy** → how this app’s APIs, rankings, and citations work together
 */

export type AssistantSuggestionCategory = {
  id: string;
  /** Short label shown in the accordion header */
  title: string;
  /** One-line scope for the category */
  subtitle: string;
  prompts: string[];
};

/** ≥25 prompts per category — keep in sync with backend intent / platform-scope behavior. */
export const ASSISTANT_SUGGESTION_CATEGORIES: AssistantSuggestionCategory[] = [
  {
    id: "focus-country-metrics",
    title: "Focus country — macro & development",
    subtitle: "Uses the selected country’s dashboard series (WDI-backed where noted)",
    prompts: [
      "Give a concise executive overview of the selected country using the latest dashboard indicators.",
      "What headline macro story do the latest platform series tell for the selected country?",
      "Summarize GDP, GDP growth, and inflation for the selected country in plain language with data years.",
      "How do nominal GDP per capita and GDP per capita at PPP compare for the selected country, and why do both matter?",
      "Describe the selected country’s government debt (% of GDP and level in US$) and what the latest year implies.",
      "Explain unemployment (ILO modelled) and labor force participation together for the selected country.",
      "How do the lending interest rate and consumer price inflation interact for the selected country in recent years?",
      "What does the real interest rate suggest about financial conditions for the selected country?",
      "Summarize life expectancy and adult literacy as human-development proxies for the selected country.",
      "How is the selected country’s population trending, and what do youth and ages 65+ shares imply?",
      "Compare international poverty headcount ($2.15, 2017 PPP) with national poverty headcount for the selected country.",
      "What does undernourishment prevalence indicate for the selected country alongside poverty lines?",
      "Walk through fiscal pressure using government debt, tax revenue, and central government expenditure (% of GDP) for the selected country.",
      "Which three dashboard indicators would you watch first as early warning for the selected country?",
      "Draft five internal talking points on the selected country’s macro picture grounded only in platform figures.",
      "Where are the main economic strengths and vulnerabilities visible in platform data for the selected country?",
      "Connect GDP growth and inflation for the selected country over the latest available years.",
      "Summarize the selected country’s external balance context using trade and reserves where the dashboard lists them.",
      "How exposed is the selected country to inflation and interest-rate stress per the dashboard series?",
      "Explain gross tertiary enrollment as a skills pipeline indicator for the selected country.",
      "Describe out-of-school rates for primary and secondary ages for the selected country if present in the snapshot.",
      "What does general government final consumption expenditure (% of GDP) suggest about the state’s role for the selected country?",
      "Compare GDP at constant prices growth with population growth to discuss per-person income dynamics for the selected country.",
      "Give a risk-and-opportunity summary for investors using only indicators available for the selected country here.",
      "If one headline number were missing from the snapshot, which adjacent series would you use to triangulate for the selected country?",
      "How would you brief a minister in two minutes using only the selected country’s labeled indicator lines?",
    ],
  },
  {
    id: "global-rankings",
    title: "Global rankings & leaderboards",
    subtitle: "Top or bottom country lists from the same snapshot pipeline as the global dashboard",
    prompts: [
      "Top 10 countries by GDP (current US$).",
      "Bottom 10 countries by GDP per capita.",
      "Top 15 countries by population.",
      "Top 10 countries by GDP growth (annual %).",
      "Top 10 countries by inflation (consumer prices).",
      "Bottom 10 countries by inflation — who shows the lowest recent consumer price changes?",
      "Top 10 countries by unemployment rate (ILO modelled).",
      "Bottom 10 countries by unemployment rate.",
      "Top 10 countries by life expectancy at birth.",
      "Bottom 10 countries by life expectancy at birth.",
      "Top 10 countries by adult literacy rate.",
      "Top 10 countries by government debt as % of GDP.",
      "Bottom 10 countries by government debt as % of GDP.",
      "Top 10 countries by poverty headcount at $2.15 a day (2017 PPP).",
      "Top 10 countries by GDP at purchasing power parity.",
      "Top 10 countries by GDP per capita at PPP.",
      "Top 12 countries by lending interest rate.",
      "Top 10 countries by real interest rate.",
      "Top 10 countries by central government expenditure as % of GDP.",
      "Top 10 countries by tax revenue as % of GDP.",
      "Top 10 most populous economies with the highest GDP per capita in the same snapshot year.",
      "Top 15 countries by undernourishment prevalence if the ranking is available this year.",
      "Bottom 15 countries by GDP per capita at PPP — who are the lowest by that measure?",
      "Top 10 countries by gross tertiary enrollment ratio.",
      "Top 10 countries by primary school enrollment.",
      "Rank the bottom 20 countries by GDP growth to find the weakest growth performers in the table.",
    ],
  },
  {
    id: "country-comparisons",
    title: "Multi-country comparisons",
    subtitle: "Side-by-side metrics — name several ISO-known economies with the selected country",
    prompts: [
      "Compare the selected country to Thailand, Singapore, the United States, Malaysia, and Germany on GDP, population, unemployment, and inflation.",
      "Compare the selected country to Brazil, India, China, Japan, and the United States on GDP, GDP per capita, and population.",
      "Compare the selected country to Vietnam, the Philippines, Indonesia, and Malaysia on GDP growth and inflation.",
      "Compare the selected country to France, Germany, Italy, Spain, and the United Kingdom on government debt % of GDP and GDP per capita.",
      "Compare the selected country to Mexico, Argentina, Chile, and Colombia on inflation and unemployment.",
      "Compare the selected country to Nigeria, South Africa, Egypt, and Kenya on population, GDP, and GDP per capita.",
      "Compare the selected country to Saudi Arabia, United Arab Emirates, Qatar, and Kuwait on GDP per capita and population.",
      "Compare the selected country to Australia, New Zealand, Canada, and the United States on life expectancy and GDP per capita.",
      "Compare the selected country to Poland, Czechia, Hungary, and Romania on GDP per capita at PPP and inflation.",
      "Compare the selected country to Bangladesh, Pakistan, and Sri Lanka on poverty headcount and population.",
      "Compare the selected country to Norway, Sweden, Denmark, and Finland on government debt and GDP per capita.",
      "Compare the selected country to Türkiye, Russia, and Iran on inflation and GDP growth if series are present.",
      "Compare the selected country to South Korea, Japan, and Australia on GDP per capita and tertiary enrollment.",
      "Compare the selected country to Portugal, Greece, and Ireland on unemployment and government debt.",
      "Compare the selected country to Canada and the United States on population, GDP, and GDP per capita.",
      "Compare the selected country to Switzerland and Austria on GDP per capita, inflation, and unemployment.",
      "Compare the selected country to Singapore and South Korea on GDP per capita at PPP and population.",
      "Compare the selected country to Chile and Peru on poverty headcount and GDP growth.",
      "Compare the selected country to Ethiopia, Tanzania, and Uganda on population and GDP per capita.",
      "Compare the selected country to Netherlands, Belgium, and Switzerland on tax revenue % of GDP and GDP per capita.",
      "Compare the selected country to Japan and South Korea on life expectancy, population ages 65+, and GDP per capita.",
      "Compare the selected country to Spain and Italy on unemployment, youth unemployment proxy via labor series, and debt.",
      "Compare the selected country to United Kingdom and France on GDP, inflation, and government debt.",
      "Compare the selected country to Indonesia and Malaysia on lending interest rate, inflation, and real interest rate.",
      "Compare the selected country to Egypt and Morocco on population, GDP growth, and inflation.",
      "Compare the selected country to Kazakhstan, Uzbekistan, and Azerbaijan on GDP per capita and inflation.",
    ],
  },
  {
    id: "current-affairs-web",
    title: "Current affairs & leadership (live web)",
    subtitle: "Time-sensitive facts — uses fresh search; avoid treating dashboard series as political news",
    prompts: [
      "Who is the current head of state or head of government of the selected country, and when did they take office?",
      "Who is the current prime minister (or chief executive) of the selected country as of today?",
      "Summarize the most recent national election or major vote in the selected country and who won, per recent reporting.",
      "What are the main political developments in the selected country over the last few months?",
      "What is the current stance of the selected country’s government on climate or energy policy in recent news?",
      "What major protests or social movements have been reported recently in the selected country?",
      "How is the selected country’s currency or FX market described in recent financial news?",
      "What did recent headlines say about the selected country’s central bank or monetary policy?",
      "What are the latest reported diplomatic developments involving the selected country and its neighbors?",
      "Summarize recent coverage of corruption or governance scandals in the selected country, with dates.",
      "What is the current composition of the ruling coalition or ruling party in the selected country?",
      "Who leads the main opposition in the selected country according to recent sources?",
      "What upcoming election or referendum is scheduled or rumored for the selected country?",
      "How is the selected country positioned in recent regional trade or integration news?",
      "What humanitarian or security issues have been reported recently in border regions of the selected country?",
      "Summarize recent international sanctions or trade measures affecting the selected country, if any.",
      "What are major infrastructure or energy projects in the news for the selected country?",
      "How is the selected country discussed in recent UN or multilateral meetings?",
      "What health or pandemic-related policy updates appeared recently for the selected country?",
      "Summarize recent judicial or constitutional controversies in the selected country.",
      "What is the latest on peace talks or conflict involving the selected country in reputable outlets?",
      "Who is the current finance or economy minister of the selected country?",
      "What tourism or travel advisories mention the selected country recently?",
      "How are labor strikes or wage disputes covered recently for the selected country?",
      "What space, tech, or innovation stories involve the selected country in the past year?",
      "What sports or cultural events put the selected country in international headlines recently?",
    ],
  },
  {
    id: "place-and-society-web",
    title: "Place, culture & society (web-first)",
    subtitle: "Geography and human context — do not pad with macro dashboard stats unless you ask for them",
    prompts: [
      "Where is the selected country on the map — region, subregion, neighbors, and capital?",
      "Describe everyday cultural norms a visitor should respect in the selected country.",
      "What languages are spoken in the selected country and where are they dominant?",
      "Outline a five-day cultural itinerary in the selected country without focusing on economic statistics.",
      "What are iconic dishes or culinary traditions associated with the selected country?",
      "Summarize major religious and ethnic diversity in the selected country at a high level.",
      "What UNESCO World Heritage or notable heritage sites belong to the selected country?",
      "How is education structured socially (not numerically) in the selected country?",
      "What are famous festivals or public holidays in the selected country?",
      "Describe traditional music, dance, or crafts associated with the selected country.",
      "What sports are most popular socially in the selected country?",
      "How do urban and rural life differ culturally in the selected country?",
      "What environmental features (mountains, coasts, rivers) define the selected country’s geography?",
      "Summarize colonial or independence history of the selected country in accessible prose.",
      "Who are widely known writers, artists, or filmmakers from the selected country?",
      "What are polite greetings and taboos to avoid when meeting people in the selected country?",
      "How is family structure commonly described in the selected country?",
      "What role do markets, bazaars, or street food play in social life in the selected country?",
      "Describe the climate zones a traveler would encounter across the selected country.",
      "What diaspora communities abroad are often linked to the selected country?",
      "How is the education calendar and school year generally organized in the selected country?",
      "What are common misconceptions foreigners have about the selected country?",
      "Recommend nonfiction or fiction books to understand the selected country’s society.",
      "How do media and press freedom compare narratively (not statistically) for the selected country?",
      "What volunteer or NGO themes are commonly associated with civil society in the selected country?",
      "What migration patterns into or out of the selected country are discussed qualitatively in sources?",
    ],
  },
  {
    id: "data-and-platform-scope",
    title: "Metric definitions (credible sources)",
    subtitle: "Definitions and interpretation of metrics across the app, grounded in World Bank/IMF/UIS and other institutions",
    prompts: [
      "Define GDP (nominal), GDP growth, and GDP per capita exactly as used in this app, with source definitions.",
      "Explain GDP per capita (PPP) versus nominal GDP per capita using World Bank/IMF definitions and practical interpretation.",
      "Define GNI per capita (Atlas method) and when it differs from GDP per capita.",
      "Define government debt (% of GDP) and nominal government debt (US$), including how to read both together.",
      "Define inflation (consumer prices, annual %) and how it differs from price level or cost-of-living narratives.",
      "Define lending rate and real interest rate, including key limitations for cross-country comparison.",
      "Define unemployment (modeled ILO estimate) and labour force total, with caveats from institutional metadata.",
      "Define population total and age-structure metrics (0–14, 15–64, 65+) and how they should be interpreted.",
      "Define life expectancy at birth and under-five mortality with formal source-aligned wording.",
      "Define maternal mortality ratio and tuberculosis incidence and what policy context they usually indicate.",
      "Define UHC service coverage index and explain what it captures versus what it does not capture.",
      "Define hospital beds, physicians density, and nurses/midwives density in per-1,000 terms.",
      "Define immunization coverage metrics (DPT and measles) and typical comparability caveats.",
      "Define health expenditure (% of GDP) and why it should not be read as spending quality by itself.",
      "Define smoking prevalence and birth rate and explain how to avoid overinterpreting short-term changes.",
      "Define international poverty headcount ($2.15/day, 2017 PPP) with source methodology context.",
      "Define national poverty headcount and explain comparability versus international poverty lines.",
      "Define literacy rate and enrollment metrics (primary/secondary/tertiary) with UIS/WDI source notes.",
      "Define out-of-school rates and completion rates, including when proxy logic may be used.",
      "Define gender parity index (primary/secondary/tertiary) and how to interpret values above/below 1.",
      "Define education expenditure (% of GDP) and key limitations in cross-country benchmarking.",
      "Define area, land area, total area, and EEZ metrics as displayed in this app.",
      "Explain what 'latest available year' means per indicator and why years can differ across metrics.",
      "Explain how YoY is computed in this app and when YoY should be treated cautiously.",
      "For each dashboard metric currently shown, give: definition, formula/unit, source institution, and interpretation caveat.",
      "Map each metric in this app to its primary institutional source (World Bank, IMF, UIS, etc.) with short definitions.",
    ],
  },
];

export const ASSISTANT_SUGGESTION_COUNT = ASSISTANT_SUGGESTION_CATEGORIES.reduce(
  (n, c) => n + c.prompts.length,
  0
);
